export const metadata = {
  title: "iKnow | Intro",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className="iknow_tm_intro">
      <div className="intro_bg" data-img-url="/img/hero/4.jpg" />
      <div className="intro_title">
        <span className="image_logo">
          <img src="/img/logo/dark.png" alt="" />
          <span className="version">V 1.0</span>
        </span>
        <span>Modern CV / Resume / Portfolio React NextJS Template</span>
      </div>
      <div className="demo">
        <ul>
          <li>
            <h3 className="name">Jessica</h3>
            <div className="list_inner">
              <div className="in">
                <img src="/img/intro/1.jpg" alt="" />
                <h3 className="mini">Light Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-1"
                  target="_blank"
                />
              </div>
              <div className="in">
                <img src="/img/intro/1-dark.jpg" alt="" />
                <h3 className="mini">Dark Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-1/dark"
                  target="_blank"
                />
              </div>
            </div>
          </li>
          <li>
            <h3 className="name">Tom</h3>
            <div className="list_inner">
              <div className="in">
                <img src="/img/intro/2.jpg" alt="" />
                <h3 className="mini">Light Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-2"
                  target="_blank"
                />
              </div>
              <div className="in">
                <img src="/img/intro/2-dark.jpg" alt="" />
                <h3 className="mini">Dark Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-2/dark"
                  target="_blank"
                />
              </div>
            </div>
          </li>
          <li>
            <h3 className="name">Sarah</h3>
            <div className="list_inner">
              <div className="in">
                <img src="/img/intro/3.jpg" alt="" />
                <h3 className="mini">Light Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-3"
                  target="_blank"
                />
              </div>
              <div className="in">
                <img src="/img/intro/3-dark.jpg" alt="" />
                <h3 className="mini">Dark Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-3/dark"
                  target="_blank"
                />
              </div>
            </div>
          </li>
          <li>
            <h3 className="name">
              <span className="name_in">
                Jassone<span className="new">New</span>
              </span>
            </h3>
            <div className="list_inner">
              <div className="in">
                <img src="/img/intro/4.jpg" alt="" />
                <h3 className="mini">Light Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-4"
                  target="_blank"
                />
              </div>
              <div className="in">
                <img src="/img/intro/4-dark.jpg" alt="" />
                <h3 className="mini">Dark Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-4/dark"
                  target="_blank"
                />
              </div>
            </div>
          </li>
          <li>
            <h3 className="name">
              <span className="name_in">
                Mary<span className="new">New</span>
              </span>
            </h3>
            <div className="list_inner">
              <div className="in">
                <img src="/img/intro/6.jpg" alt="" />
                <h3 className="mini">Light Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-6"
                  target="_blank"
                />
              </div>
              <div className="in">
                <img src="/img/intro/6-dark.jpg" alt="" />
                <h3 className="mini">Dark Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-6/dark"
                  target="_blank"
                />
              </div>
            </div>
          </li>
          <li>
            <h3 className="name">
              <span className="name_in">
                James<span className="new">New</span>
              </span>
            </h3>
            <div className="list_inner">
              <div className="in">
                <img src="/img/intro/5.jpg" alt="" />
                <h3 className="mini">Light Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-5"
                  target="_blank"
                />
              </div>
              <div className="in">
                <img src="/img/intro/5-dark.jpg" alt="" />
                <h3 className="mini">Dark Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-5/dark"
                  target="_blank"
                />
              </div>
            </div>
          </li>
          <li>
            <h3 className="name">
              <span className="name_in">
                Nayna<span className="new">New</span>
              </span>
            </h3>
            <div className="list_inner">
              <div className="in">
                <img src="/img/intro/7.jpg" alt="" />
                <h3 className="mini">Light Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-7"
                  target="_blank"
                />
              </div>
              <div className="in">
                <img src="/img/intro/7-dark.jpg" alt="" />
                <h3 className="mini">Dark Demo</h3>
                <a
                  className="iknow_tm_full_link"
                  href="index-7/dark"
                  target="_blank"
                />
              </div>
            </div>
          </li>
        </ul>
        <div className="coming">
          <h3>More are coming soon...</h3>
        </div>
      </div>
      <div className="intro_space" />
    </div>
  );
};
export default page;
