export const shapes1 = [
  { id: 1, classname: "one", animationName: "anim_scale", shapeImg: "9" },
  {
    id: 2,
    classname: "two",
    animationName: "anim_moveLeft",
    shapeImg: "dot",
  },
  {
    id: 3,
    classname: "three",
    animationName: "anim_moveLeft",
    shapeImg: "dot-2",
  },
  {
    id: 4,
    classname: "four",
    animationName: "anim_circle",
    shapeImg: "1",
  },
  {
    id: 5,
    classname: "five",
    animationName: "anim_circle",
    shapeImg: "8",
  },
  {
    id: 6,
    classname: "six",
    animationName: "anim_circle",
    shapeImg: "3",
  },
  {
    id: 7,
    classname: "seven",
    animationName: "anim_right",
    shapeImg: "4",
  },
  {
    id: 8,
    classname: "eight",
    animationName: "anim_scale",
    shapeImg: "9",
  },
  {
    id: 9,
    classname: "nine",
    animationName: "anim_circle",
    shapeImg: "3",
  },
  {
    id: 10,
    classname: "ten",
    animationName: "anim_moveLeft",
    shapeImg: "4",
  },
  {
    id: 11,
    classname: "eleven",
    animationName: "anim_scale",
    shapeImg: "9",
  },
  {
    id: 12,
    classname: "twelve",
    animationName: "anim_extra",
    shapeImg: "2",
  },
  {
    id: 13,
    classname: "thirteen",
    animationName: "anim_circle",
    shapeImg: "5",
  },
  {
    id: 14,
    classname: "fourteen",
    animationName: "anim_scale",
    shapeImg: "9",
  },
  {
    id: 15,
    classname: "fifteen",
    animationName: "anim_circle",
    shapeImg: "3",
  },
  {
    id: 16,
    classname: "sixteen",
    animationName: "anim_scale",
    shapeImg: "9",
  },
  {
    id: 17,
    classname: "seventeen",
    animationName: "anim_circle",
    shapeImg: "5",
  },
  {
    id: 18,
    classname: "eighteen",
    animationName: "anim_scale",
    shapeImg: "9",
  },
  {
    id: 19,
    classname: "nineteen",
    animationName: "anim_scale",
    shapeImg: "9",
  },
  {
    id: 20,
    classname: "twenty",
    animationName: "anim_circle",
    shapeImg: "1",
  },
];

export const shapes2 = [
  {
    id: 1,
    classname: "one",
    animationName: "anim_circle",
    shapeImg: "11",
  },
  {
    id: 2,
    classname: "two",
    animationName: "anim_scale2",
    shapeImg: "10",
  },
  {
    id: 3,
    classname: "three",
    animationName: "anim_scale2",
    shapeImg: "6",
  },
  {
    id: 4,
    classname: "four",
    animationName: "anim_scale2",
    shapeImg: "6",
  },
  {
    id: 5,
    classname: "five",
    animationName: "anim_scale",
    shapeImg: "11",
  },
  {
    id: 6,
    classname: "six",
    animationName: "anim_scale2",
    shapeImg: "10",
  },
  {
    id: 7,
    classname: "seven",
    animationName: "anim_scale2",
    shapeImg: "6",
  },
  {
    id: 8,
    classname: "eight",
    animationName: "anim_scale2",
    shapeImg: "10",
  },
  {
    id: 9,
    classname: "nine",
    animationName: "anim_scale2",
    shapeImg: "6",
  },
  {
    id: 10,
    classname: "ten",
    animationName: "anim_scale2",
    shapeImg: "10",
  },
  {
    id: 11,
    classname: "eleven",
    animationName: "anim_circle",
    shapeImg: "11",
  },
  {
    id: 12,
    classname: "twelve",
    animationName: "anim_circle",
    shapeImg: "11",
  },
  {
    id: 13,
    classname: "thirteen",
    animationName: "anim_scale2",
    shapeImg: "6",
  },
  {
    id: 14,
    classname: "fourteen",
    animationName: "anim_circle",
    shapeImg: "11",
  },
  {
    id: 15,
    classname: "fifteen",
    animationName: "anim_scale2",
    shapeImg: "6",
  },
  {
    id: 16,
    classname: "sixteen",
    animationName: "anim_scale2",
    shapeImg: "10",
  },
  {
    id: 17,
    classname: "seventeen",
    animationName: "anim_scale2",
    shapeImg: "10",
  },
  {
    id: 18,
    classname: "eighteen",
    animationName: "anim_scale2",
    shapeImg: "10",
  },
];
